#!/bin/bash
python3 -c "w='$WATER';s='$STIR';d={'w':0,'a':1,'t':2,'e':3,'r':4,'s':0,'t':1,'i':2,'r':3};wd=sum(d[c]*5**i for i,c in enumerate(w[::-1]) if c in 'water');sd=sum(d[c]*4**i for i,c in enumerate(s[::-1]) if c in 'stir');t=wd+sd;b='bestchol';print(''.join(b[t>>3*i&7] for i in range((t.bit_length()+2)//3)[::-1]) or 'b')"
